
function writeBatchfile(dirString)
% Write batchfile for PBS submission

idFile = fopen(strcat(dirString,'/batchfile'),'wt');

fprintf(idFile, ...
 ['#PBS -N ' dirString ' \n' ...
  '#PBS -q oh \n'...
  '#PBS -l nodes=8 \n' ...
  '#PBS -l walltime=72:00:00 \n' ...
  '#PBS -l mem=15gb \n' ...
  '#PBS -m bea \n' ...
  '#PBS -M 332084@swansea.ac.uk \n' ...
  'cd ' strcat(pwd, '/', dirString)  '\n' ...
  'mpiexec /eng/cvcluster/egevansbj/codes/Boltzmann/BGKcode2016/BGK > output \n']) ;
 
 fclose(idFile) ;
 
end
